"""Batch 6 (final): rememberIt / studentQuestions / formulas for ALL remaining concepts."""
import json, os, glob

ROOT = os.path.join(os.path.dirname(__file__), "..", "content-packs")
INDEX = {}
for f in glob.glob(os.path.join(ROOT, "*", "concepts", "*.json")):
    INDEX[os.path.basename(f)[:-5]] = f

def R(hook, unpack):
    return {"hook": hook, "unpack": unpack}
def Q(*pairs):
    return [{"q": q, "a": a} for q, a in pairs]

DATA = {
  "data-01-bar-graphs": {"rememberIt": R("Bars compare amounts - taller bar = more",
    "Read the top of each bar against the scale. Bars have equal width with gaps. Great for comparing categories."),
    "studentQuestions": Q(("How do I read a bar graph?", "Find the top of the bar, read straight across to the scale number. Taller = more."),
                          ("Bar graph or pictograph?", "Bars show exact amounts on a scale; pictographs use pictures where each stands for a number."))},
  "data-02-collecting-data": {"rememberIt": R("Tally in fives: four lines, then a slash across",
    "|||| with a diagonal = 5. Collect, tally, then count in 5s. A table organises the raw data first."),
    "studentQuestions": Q(("Why tally in groups of five?", "The 5th mark slashes across the four, so you count in fast 5s and rarely miscount."),
                          ("What's the first step with data?", "Collect it, then organise into a tally table before drawing any graph."))},
  "data-03-pictograph": {"rememberIt": R("Each picture stands for a number - check the KEY",
    "If 1 apple = 10, then 3 apples = 30. Half a picture = half the value. Always read the key first."),
    "studentQuestions": Q(("Why is there a key?", "One picture often stands for many (1 = 10). The key tells you how many, so you can multiply."),
                          ("What does half a symbol mean?", "Half the value - if a whole star = 10, half a star = 5."))},
  "data-04-smart-charts": {"rememberIt": R("Pick the chart that fits the question",
    "Bar = compare groups. Line = change over time. Pie = parts of a whole. Pictograph = fun counts."),
    "studentQuestions": Q(("Which chart should I use?", "Comparing groups -> bar. Change over time -> line. Parts of a whole -> pie."),
                          ("What makes a chart 'smart'?", "It matches the data to the right picture so the message is instantly clear."))},
  "data-07-probability-depth": {"rememberIt": R("Combine events: AND multiplies, OR adds",
    "P(A and B) = P(A) x P(B) for independent events. P(A or B) = P(A) + P(B) - P(both)."),
    "studentQuestions": Q(("AND or OR - which operation?", "'AND' (both happen) -> multiply. 'OR' (either happens) -> add, then subtract the overlap."),
                          ("What are independent events?", "Events where one does not affect the other, like two coin flips. Just multiply their probabilities."))},
  "data-08-grouped-statistics": {"rememberIt": R("Grouped data: use class MIDPOINTS as the values",
    "Mean = sum(f x midpoint) / sum(f). Modal class = highest frequency; median class is where the running total passes halfway."),
    "studentQuestions": Q(("How do I find the mean of grouped data?", "Use each class midpoint as its value, multiply by frequency, add up, divide by total frequency."),
                          ("What is a 'class'?", "A range of values grouped together (like 10-20). Its midpoint stands in for all values in it."))},
  "data-10-probability-axiomatic": {"rememberIt": R("Three rules: P >= 0, P(sure) = 1, add for mutually exclusive",
    "Every probability is between 0 and 1; the whole sample space totals 1; for events that cannot both happen, P(A or B) = P(A) + P(B)."),
    "studentQuestions": Q(("What does 'axiomatic' mean here?", "Probability built from a few basic rules rather than just counting, so everything stays consistent."),
                          ("What is the sample space?", "The set of ALL possible outcomes. Its total probability is always 1."))},
  "data-11-conditional-probability": {"rememberIt": R("P(A given B) = P(A and B) / P(B) - the world shrinks to B",
    "Once B has happened, only B's outcomes count. Bayes flips the condition between P(A|B) and P(B|A)."),
    "studentQuestions": Q(("What does 'given' mean?", "We already KNOW B happened, so we only look inside B's outcomes - the total shrinks to B."),
                          ("Why divide by P(B)?", "Because B is now our whole world; we rescale so the probabilities inside B add to 1."))},
  "dec-02-money-decimals": {"rememberIt": R("Money is decimals: rupees.paise, two places after the dot",
    "12.50 = 12 rupees, 50 paise. Line up the dots to add. 100 paise = 1 rupee."),
    "studentQuestions": Q(("Why two digits after the dot for money?", "Paise are hundredths of a rupee - two decimal places. 5.05 is five rupees and five paise."),
                          ("How do I add money?", "Line up the decimal points, then add like normal decimals - paise under paise."))},
  "dec-03-hundredths": {"rememberIt": R("Second place after the dot = hundredths (1/100)",
    "0.07 = 7 hundredths = 7/100. 0.25 = 25/100 = 1/4. Two decimal places means hundredths."),
    "studentQuestions": Q(("What does the second decimal place mean?", "Hundredths - one of 100 equal pieces. 0.03 is 3 hundredths, 3/100."),
                          ("Is 0.25 a quarter?", "Yes - 25 hundredths (25/100) simplifies to 1/4."))},
  "dec-04-fraction-decimal-link": {"rememberIt": R("Fraction to decimal: divide top by bottom",
    "3/4 = 3 / 4 = 0.75. 1/2 = 0.5, 1/4 = 0.25, 1/10 = 0.1. Two ways to write the same amount."),
    "studentQuestions": Q(("How do I turn a fraction into a decimal?", "Divide the top by the bottom. 3/5 = 3 / 5 = 0.6."),
                          ("Is 0.5 the same as 1/2?", "Yes - two ways of writing 'one half'. Fractions and decimals are the same thing dressed differently."))},
  "frac-02-numberline": {"rememberIt": R("Fractions live BETWEEN whole numbers on the line",
    "Split the gap 0 to 1 into equal steps. 3/4 is the third step of four. Bigger bottom = smaller steps."),
    "studentQuestions": Q(("Where does 3/4 go on the number line?", "Between 0 and 1: split that gap into 4 equal parts and count 3 steps."),
                          ("Which is bigger, 1/2 or 3/4?", "3/4 - it sits further right, closer to 1."))},
  "frac-04-comparing": {"rememberIt": R("Same bottom? Bigger top wins. Different bottoms? Make them same",
    "2/5 vs 3/5 -> 3/5 bigger. 2/3 vs 3/4 -> common bottom 12: 8/12 vs 9/12 -> 3/4 bigger. Or cross-multiply."),
    "studentQuestions": Q(("How do I compare 2/3 and 3/4?", "Common bottom 12: 8/12 vs 9/12, so 3/4 is bigger. Or cross-multiply: 2x4=8, 3x3=9."),
                          ("Same bottom - which is bigger?", "The one with the bigger top. More pieces of the same size = more."))},
  "frac-07-mixed-numbers": {"rememberIt": R("Mixed number = whole + fraction. To improper: whole x bottom + top",
    "2 1/3 = (2x3 + 1)/3 = 7/3. Back again: divide - the whole is the quotient, remainder over the bottom."),
    "studentQuestions": Q(("How do I turn 2 1/3 into an improper fraction?", "Whole times bottom plus top, over the bottom: (2x3 + 1)/3 = 7/3."),
                          ("Why use improper fractions?", "They are easier to multiply and divide. Convert back to mixed only at the end to read the answer."))},
  "geo-01-shapes": {"rememberIt": R("Name 2D shapes by their sides and corners",
    "Triangle 3, quadrilateral 4, pentagon 5, hexagon 6. Same number of sides and corners. A circle has no corners."),
    "studentQuestions": Q(("Sides and corners - are they equal?", "For straight-sided shapes, yes - a 4-sided shape has 4 corners."),
                          ("Is a circle a polygon?", "No - polygons have straight sides. A circle is one smooth curve."))},
  "geo-03-area": {"rememberIt": R("Area = space inside (square units). Count or multiply squares",
    "Rectangle area = length x breadth, measured in square units (cm^2). Different from perimeter (the edge)."),
    "studentQuestions": Q(("Area or perimeter?", "Area is the space INSIDE (square units); perimeter is the distance AROUND (length units)."),
                          ("Why 'square' units?", "Because we count how many unit SQUARES fit inside - so cm^2, m^2, etc."))},
  "geo-04-symmetry": {"rememberIt": R("A line of symmetry = a fold where both halves match",
    "Fold and the two sides land exactly on each other. A square has 4 lines; a circle infinite; the letter A has 1."),
    "studentQuestions": Q(("How do I find a line of symmetry?", "Imagine folding the shape - if the two halves match exactly, that fold line is a line of symmetry."),
                          ("Do all shapes have symmetry?", "No. A scalene triangle has none; a circle has infinitely many."))},
  "geo-06-solids-nets": {"rememberIt": R("A net is a solid unfolded flat - fold it back up",
    "A cube's net = 6 squares. Match each flat face to the folded solid. Count faces, edges, corners."),
    "studentQuestions": Q(("What is a net?", "A flat pattern that folds up into a 3D solid. A cube's net is six connected squares."),
                          ("How many faces does a cube have?", "6 - one per square in its net. Also 12 edges and 8 corners."))},
  "geo-07-3d-shapes": {"rememberIt": R("3D shapes: count Faces, Edges, Vertices (corners)",
    "Cube: 6 faces, 12 edges, 8 vertices. Euler: F + V - E = 2 for solids. Curved solids (sphere) have no edges."),
    "studentQuestions": Q(("Face, edge, vertex - what's what?", "Face = a flat surface; edge = where two faces meet (a line); vertex = a corner point."),
                          ("Does a sphere have edges?", "No - it is one smooth curved surface, no flat faces, edges, or corners."))},
  "geo-08-area-boundary": {"rememberIt": R("Boundary = perimeter (around). Region = area (inside)",
    "Fence = boundary (length units). Grass = area (square units). Do not mix them up."),
    "studentQuestions": Q(("Boundary or region?", "Boundary is the edge you walk around (perimeter); region is the surface inside (area)."),
                          ("Which uses square units?", "Area (the region). Boundary/perimeter uses plain length units like m or cm."))},
  "geo-09-lines-angles": {"rememberIt": R("Angles on a line = 180. Around a point = 360. Vertically opposite are equal",
    "Parallel lines cut by a line: corresponding (F-angles) and alternate (Z-angles) are equal."),
    "studentQuestions": Q(("What do angles on a straight line add to?", "180 degrees. So if one is 130, the other is 50."),
                          ("What are vertically opposite angles?", "The equal angles opposite each other where two lines cross - always equal."))},
  "geo-10-triangles-quads": {"rememberIt": R("Triangle angles add to 180; quadrilateral to 360",
    "Triangles by sides (equilateral/isosceles/scalene) and angles (acute/right/obtuse). Quad angle sum = 360."),
    "studentQuestions": Q(("Why do a triangle's angles add to 180?", "Tear off the three corners and place them together - they form a straight line, which is 180 degrees."),
                          ("What do a quadrilateral's angles add to?", "360 degrees - it splits into two triangles, 180 + 180."))},
  "geo-12-congruence-similarity": {"rememberIt": R("Congruent = same shape AND size. Similar = same shape, scaled",
    "Congruent copies match exactly (SSS, SAS, ASA, RHS). Similar shapes share equal angles and sides in the same ratio."),
    "studentQuestions": Q(("Congruent vs similar?", "Congruent = identical (same size). Similar = same shape but bigger or smaller (scaled)."),
                          ("What is a congruence rule?", "A shortcut proving two triangles identical: SSS, SAS, ASA, or RHS - without checking all six measurements."))},
  "geo-19-circle-tangents": {"rememberIt": R("A tangent touches at ONE point, perpendicular to the radius there",
    "Two tangents from an outside point are equal in length. Radius meets tangent at 90 degrees."),
    "studentQuestions": Q(("What's special about a tangent and the radius?", "They meet at exactly 90 degrees at the point of contact - always a right angle."),
                          ("Two tangents from one point?", "They are equal in length - the point is the same distance along each."))},
  "geo-20-areas-circles": {"rememberIt": R("Sector = pizza slice. Area = (angle/360) x pi r^2",
    "Arc length = (angle/360) x 2 pi r. A sector is a fraction of the whole circle - the fraction is angle/360."),
    "studentQuestions": Q(("How do I find a sector's area?", "Take its fraction of the circle (its angle out of 360) times the full area pi r^2."),
                          ("Sector vs segment?", "Sector = slice between two radii (pizza slice). Segment = the piece cut off by a chord (the crust)."))},
  "geo-22-constructions": {"rememberIt": R("Ruler + compass only - no measuring angles",
    "Perpendicular bisector: equal arcs from both ends. Angle bisector: arcs from the vertex. Keep the compass width fixed per step."),
    "studentQuestions": Q(("Why only compass and ruler?", "Classical constructions test exact geometry, not measurement - the compass copies lengths perfectly."),
                          ("How do I bisect a line?", "Open the compass past halfway, draw arcs from both ends above and below, join where they cross."))},
  "geo-23-euclid-geometry": {"rememberIt": R("Axioms = obvious truths we agree on; theorems are proved from them",
    "Euclid's postulates build all of geometry. 'Things equal to the same thing are equal to each other.'"),
    "studentQuestions": Q(("What is an axiom?", "A basic truth accepted without proof (like 'the whole is greater than the part'). Everything else is proved from these."),
                          ("Axiom vs theorem?", "An axiom is assumed true; a theorem is PROVED true using axioms and logic."))},
  "geo-24-straight-lines": {"rememberIt": R("y = mx + c: m is the slope, c is where it crosses the y-axis",
    "Slope m = rise/run. Positive rises, negative falls. Parallel lines share m; perpendicular slopes multiply to -1."),
    "studentQuestions": Q(("What do m and c mean?", "m is the steepness (slope); c is the y-intercept (where the line meets the y-axis)."),
                          ("How do I know two lines are perpendicular?", "Their slopes multiply to -1 (e.g. 2 and -1/2). Parallel lines have the SAME slope.")),
    "formulas": [{"name": "Slope", "formula": "m = (y2 - y1)/(x2 - x1)", "remember": "rise over run"},
                 {"name": "Line", "formula": "y = m x + c", "remember": "m = slope, c = y-intercept"}]},
  "geo-25-conic-sections": {"rememberIt": R("One cone, four cuts: circle, ellipse, parabola, hyperbola",
    "Cut level -> circle; tilt -> ellipse; parallel to the slant -> parabola; steep -> hyperbola."),
    "studentQuestions": Q(("How do I tell the four apart from equations?", "x^2+y^2 = circle; one squared term = parabola; both added = ellipse; a minus sign = hyperbola."),
                          ("Where do I see these?", "Orbits are ellipses; a thrown ball and a satellite dish are parabolas; a circle is everywhere."))},
  "geo-26-3d-geometry-intro": {"rememberIt": R("Space needs THREE numbers (x, y, z). Distance = sqrt(x^2+y^2+z^2)",
    "Three axes, 8 octants. Distance is 3D Pythagoras: square the three coordinates, add, take the root."),
    "studentQuestions": Q(("Why three numbers in space?", "Left-right, forward-back, AND up-down - three directions, so three coordinates."),
                          ("How far is (2,3,6) from the origin?", "sqrt(4+9+36) = sqrt(49) = 7 - Pythagoras with three squares."))},
  "geo-27-vectors": {"rememberIt": R("Vector = arrow with size AND direction. Add tip-to-tail",
    "Magnitude |(a,b)| = sqrt(a^2+b^2). Add components. Dot product a.b = 0 means perpendicular."),
    "studentQuestions": Q(("How is a vector different from a number?", "A number is just size; a vector also has DIRECTION, like an arrow. Force and velocity are vectors."),
                          ("What does a dot product of 0 mean?", "The two vectors are perpendicular (at right angles)."))},
  "geo-28-3d-lines-planes": {"rememberIt": R("A line needs a point + a direction; a plane needs a point + a normal",
    "Line: r = a + t d. Plane: n . (r - a) = 0. The normal n sticks straight out of the plane."),
    "studentQuestions": Q(("What is a 'normal' to a plane?", "A vector sticking straight out of the plane at 90 degrees - it fixes the plane's tilt."),
                          ("How is a line written in 3D?", "Start point plus a multiple of a direction vector: r = a + t d, where t slides you along the line."))},
  "meas-01-units": {"rememberIt": R("Match the unit to the size: mm, cm, m, km",
    "Small -> mm/cm, rooms -> m, journeys -> km. Weight: g, kg. Liquid: ml, l. Pick the sensible one."),
    "studentQuestions": Q(("Which unit for a pencil?", "Centimetres - small and handy. A road would be kilometres; a book's mass, grams."),
                          ("How are metric units linked?", "By 10s and 1000s: 10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km."))},
  "meas-02-time": {"rememberIt": R("60 seconds = 1 minute, 60 minutes = 1 hour, 24 hours = 1 day",
    "Analog: count minutes in 5s. 24-hour: after noon add 12 (2 pm = 14:00). Elapsed time: count on."),
    "studentQuestions": Q(("How do I convert 2 pm to 24-hour?", "Add 12 to afternoon times: 2 pm = 14:00. Morning stays the same (9 am = 09:00)."),
                          ("How do I find elapsed time?", "Count on from start to end, hours then minutes - 3:40 to 5:10 is 1 hour 30 minutes."))},
  "meas-03-maps-scale": {"rememberIt": R("Scale tells real size: map distance x scale = real distance",
    "Scale 1:1000 means 1 cm stands for 1000 cm (10 m). Multiply the map measurement by the scale."),
    "studentQuestions": Q(("What does a scale of 1:100 mean?", "1 unit on the map = 100 real units. 3 cm on the map is 300 cm (3 m) in real life."),
                          ("How do I find real distance?", "Measure on the map, then multiply by the scale number."))},
  "meas-04-volume": {"rememberIt": R("Volume = space inside a solid (cube units). Box = l x b x h",
    "1 litre = 1000 ml = 1000 cm^3. Capacity is how much a container holds."),
    "studentQuestions": Q(("Volume vs capacity?", "Volume is the space a solid takes; capacity is how much a container can HOLD. Often measured the same way."),
                          ("How many ml in a litre?", "1000. And 1 cm^3 = 1 ml, so a 1-litre box is 1000 cm^3.")),
    "formulas": [{"name": "Box volume", "formula": "V = l x b x h"}]},
  "meas-05-money": {"rememberIt": R("Rupees and paise: add the same columns, count change UP",
    "100 paise = 1 rupee. Line up decimal points. Change = count up from cost to cash given."),
    "studentQuestions": Q(("How do I give change?", "Count UP from the price to the money paid. Cost 65, paid 100: 65->70->100 is 35."),
                          ("How do I add amounts of money?", "Line up the decimal points and add like decimals - paise under paise, rupees under rupees."))},
  "meas-07-financial-literacy": {"rememberIt": R("Needs before wants. Income - spending = savings",
    "Budget: plan where money goes. Interest earns you money when saving, costs you money when borrowing."),
    "studentQuestions": Q(("What is a budget?", "A plan for your money: income in, spending out, savings set aside. It stops money 'disappearing'."),
                          ("Need or want?", "A need is essential (food, school); a want is nice-to-have (a toy). Budget needs first."))},
  "meas-09-advanced-finance": {"rememberIt": R("Simple interest is on the original; compound is on the growing total",
    "SI = PRT/100. Compound grows faster - interest on interest. Rule of 72: 72/rate = years to double."),
    "studentQuestions": Q(("Simple vs compound interest?", "Simple is always on the starting amount; compound adds interest onto interest, so it snowballs."),
                          ("What is the Rule of 72?", "Divide 72 by the interest rate to estimate the years for money to double. At 8%, about 9 years.")),
    "formulas": [{"name": "Simple interest", "formula": "SI = P x R x T / 100"},
                 {"name": "Compound amount", "formula": "A = P(1 + R/100)^T", "remember": "Interest on interest"}]},
  "num-02-comparing": {"rememberIt": R("Compare from the LEFT: more digits wins; same length, go digit by digit",
    "> and < point to the SMALLER number. 'The crocodile mouth eats the bigger number.'"),
    "studentQuestions": Q(("How do I compare 452 and 460?", "Same length, so left to right: hundreds equal, tens 5 vs 6 -> 460 is bigger."),
                          ("Which way does > point?", "The wide open mouth faces the BIGGER number. 7 > 3."))},
  "num-04-place-value-6digit": {"rememberIt": R("Indian system: group with commas - ones, thousands, lakhs",
    "12,34,567: commas after 3 digits then every 2. Each place is still ten times the one to its right."),
    "studentQuestions": Q(("Where do the commas go in Indian numbers?", "After 3 digits, then every 2: 12,34,567 - marking ones, thousands, then lakhs."),
                          ("What is the value of 5 in 5,00,000?", "Five lakhs. Same digit, different worth, depending on its place."))},
  "num-17-patterns": {"rememberIt": R("Find the RULE, then extend the pattern",
    "Look at the jump between terms. 2,4,6 adds 2; 3,9,27 times 3. State the rule, then continue it."),
    "studentQuestions": Q(("How do I find the next number?", "Work out what changes each step (add, subtract, multiply), then apply that rule again."),
                          ("What kinds of number patterns are there?", "Adding a constant (2,4,6), multiplying (2,4,8), squares (1,4,9), and more."))},
  "num-18-patterns": {"rememberIt": R("Growing patterns add a bit each time - count the change",
    "Match shapes to the term number. 1,3,5 (odd) or 1,3,6,10 (triangular). Find the rule linking position to value."),
    "studentQuestions": Q(("How do I link the shape to its number?", "Count the objects at each step and see how the count grows with the position - that is the rule."),
                          ("What is a triangular number?", "Dots that make triangles: 1,3,6,10... each adds the next counting number."))},
  "num-19-large-numbers": {"rememberIt": R("Big numbers: group in 3s/2s, name by place (thousand, lakh, crore)",
    "1 lakh = 100,000; 1 crore = 10,000,000 = 100 lakh. Commas tell you where each group sits."),
    "studentQuestions": Q(("How big is a crore?", "One crore = 10,000,000 (ten million) = 100 lakh. Commas group the digits so you can name it."),
                          ("How do I read a huge number?", "Group the digits, then name each group from the left: crore, lakh, thousand, ones."))},
  "num-20-patterns": {"rememberIt": R("Special sequences: squares, cubes, Fibonacci",
    "Squares 1,4,9,16. Cubes 1,8,27. Fibonacci 1,1,2,3,5,8 (add the last two). Recognise them on sight."),
    "studentQuestions": Q(("What is the Fibonacci pattern?", "Each number is the sum of the two before it: 1,1,2,3,5,8,13. It appears all over nature."),
                          ("How do I spot square numbers?", "1,4,9,16,25 - counting numbers times themselves. The gaps grow by odd numbers (3,5,7)."))},
  "num-30-number-systems": {"rememberIt": R("The number family: naturals, whole, integers, rationals, reals",
    "Naturals 1,2,3; add 0 -> whole; add negatives -> integers; add fractions -> rationals; add irrationals -> reals."),
    "studentQuestions": Q(("Whole numbers vs integers?", "Whole numbers are 0,1,2,3... Integers add the negatives: ...-2,-1,0,1,2..."),
                          ("Where do fractions fit?", "They are rational numbers (any p/q). With irrationals like sqrt 2 they make the reals."))},
  "num-31-proportion": {"rememberIt": R("Proportion = two equal ratios. Cross-multiply to solve",
    "a/b = c/d means ad = bc. Direct: both grow together. Inverse: one up, other down (speed vs time)."),
    "studentQuestions": Q(("How do I solve a/b = c/x?", "Cross-multiply: a x = b c, then divide. It finds the value that keeps the ratio equal."),
                          ("Direct or inverse proportion?", "Direct: more of one, more of the other (more items, more cost). Inverse: faster speed, less time."))},
  "num-36-functions-graphs": {"rememberIt": R("A function = a machine: one input -> one output",
    "f(x) is the output for input x. Graph it: x across, f(x) up. The vertical line test checks it is a function."),
    "studentQuestions": Q(("What is f(x)?", "The output of the machine when you feed in x. f(3) means 'the value when x = 3'."),
                          ("How do I know a graph is a function?", "The vertical line test: any vertical line hits the graph at most once (one input, one output)."))},
  "num-37-sets-logic": {"rememberIt": R("Set = a collection. Union (OR, all), Intersection (AND, shared)",
    "A U B = everything in either. A n B = only what is in both. Venn diagrams show it - AND = the overlap."),
    "studentQuestions": Q(("Union or intersection?", "Union (U) is EVERYTHING in either set (OR). Intersection (n) is only the SHARED part (AND)."),
                          ("What does a Venn diagram show?", "Overlapping circles: the overlap is the intersection (in both); the whole is the union."))},
  "num-38-modeling": {"rememberIt": R("Modelling = turn a real problem into maths, solve, then check it makes sense",
    "Steps: understand -> represent with an equation or graph -> solve -> interpret back in the real world."),
    "studentQuestions": Q(("What is mathematical modelling?", "Describing a real situation with maths, solving it, then checking the answer makes real-world sense."),
                          ("Why check against reality?", "Maths can give a silly answer in context (like 2.5 buses). Interpreting keeps it sensible."))},
  "num-39-computational-thinking": {"rememberIt": R("Break big problems into small steps (an algorithm)",
    "Decompose (split up), spot patterns, ignore the irrelevant (abstraction), write clear steps (algorithm)."),
    "studentQuestions": Q(("What is an algorithm?", "A clear list of steps that solves a problem - like a recipe a computer or person can follow exactly."),
                          ("What is decomposition?", "Breaking a big problem into smaller, easier parts you can solve one at a time."))},
  "num-43-relations-functions": {"rememberIt": R("Relation = any pairing; function = each input has exactly ONE output",
    "Domain = inputs, range = outputs. One-one and onto describe how inputs map to outputs."),
    "studentQuestions": Q(("Relation vs function?", "A relation just pairs things up; a FUNCTION is a relation where every input gives exactly one output."),
                          ("What are domain and range?", "Domain = all allowed inputs; range = all outputs the function actually produces."))},
  "num-54-application-derivatives": {"rememberIt": R("Derivative = slope. Zero slope = a max or min (turning point)",
    "Solve f'(x) = 0 for peaks/valleys. f'' tells which: negative = peak (max), positive = valley (min). Also gives rates."),
    "studentQuestions": Q(("How do I find a maximum or minimum?", "Where the slope is zero: solve f'(x) = 0. Then f''(x) tells max (negative) or min (positive)."),
                          ("What else are derivatives used for?", "Rates of change - speed from distance, how fast a tank fills, marginal cost."))},
  "num-56-application-integrals": {"rememberIt": R("Definite integral = area under the curve between limits",
    "Area = integral a..b of f dx = F(b) - F(a). Also gives distance from speed, and volumes of revolution."),
    "studentQuestions": Q(("What does a definite integral give me?", "The area under the curve between two x-values - and by extension distance from a speed graph, or a volume."),
                          ("Why F(b) - F(a)?", "Find the antiderivative F, then subtract its value at the bottom limit from the top - that nets the area."))},
  "num-57-differential-equations": {"rememberIt": R("A differential equation links a quantity to its RATE of change",
    "dy/dx = ... . Separate variables (y one side, x the other), integrate both sides. +C is fixed by initial conditions."),
    "studentQuestions": Q(("What is a differential equation?", "An equation with a derivative in it - it describes how something changes (growth, cooling, motion)."),
                          ("How do I solve a simple one?", "Separate the variables, integrate both sides, then use the given conditions to find C."))},
  "num-58-linear-programming": {"rememberIt": R("Best value sits at a CORNER of the feasible region",
    "Draw the constraints, shade the allowed region, then test each corner in the objective - the max/min is at a vertex."),
    "studentQuestions": Q(("Where is the maximum profit?", "At a corner (vertex) of the feasible region. Test each corner in the objective and pick the best."),
                          ("What is the feasible region?", "The area satisfying ALL constraints at once - where every rule is obeyed. The answer lives on its corners."))},
  "ops-07-addition-regrouping": {"rememberIt": R("When a column makes 10 or more, carry the ten to the next column",
    "Add the ones; if 10 or more, write the ones digit and carry 1 ten. Work right to left."),
    "studentQuestions": Q(("What is 'carrying'?", "When a column adds to 10+, the extra ten carries to the next column left. 8+5=13: write 3, carry 1."),
                          ("Which column do I start with?", "The ones (rightmost), then move left, so carries land in a column you have not added yet."))},
  "ops-08-subtraction-regrouping": {"rememberIt": R("Can't subtract? Borrow ten from the next column",
    "If the top digit is too small, take 1 from the column to the left (it becomes 10 more here). Work right to left."),
    "studentQuestions": Q(("What is 'borrowing'?", "When the top digit is smaller, take 1 from the next column left - it adds 10 here so you can subtract."),
                          ("42 - 17, how?", "Ones: 2-7 can't, borrow -> 12-7=5; tens: 3-1=2. Answer 25."))},
  "ops-09-multiplication-groups": {"rememberIt": R("Multiply = equal groups added fast. 4 x 3 = four groups of 3",
    "3+3+3+3 = 4 x 3 = 12. Rows x columns in an array. Order does not matter (4x3 = 3x4)."),
    "studentQuestions": Q(("What does 4 x 3 mean?", "Four groups of 3 (or 3 added four times) = 12. Multiplication is repeated equal-group adding."),
                          ("Is 4 x 3 the same as 3 x 4?", "Yes - both make 12. You can swap the numbers."))},
  "ops-11-area-multiplication": {"rememberIt": R("Area/box method: split into tens and ones, multiply the parts",
    "23 x 14 = (20+3)(10+4) = 200+80+30+12 = 322. A box grid shows every part."),
    "studentQuestions": Q(("How does the box method work?", "Split each number into tens and ones, multiply every pair, add them all - the distributive law as a grid."),
                          ("Why split into tens and ones?", "Small multiplications are easy; the box keeps track so you do not miss any part."))},
  "ops-12-mult-2x2": {"rememberIt": R("Long multiplication: multiply by ones, then tens (shift a place), add",
    "23 x 14: 23x4 = 92, then 23x10 = 230 (write a 0 first), add 92 + 230 = 322."),
    "studentQuestions": Q(("Why put a 0 on the second line?", "The second digit is TENS, so its answer is ten times bigger - the 0 shifts it into the tens place."),
                          ("How do I do 23 x 14?", "23x4 = 92, then 23x10 = 230, add: 322."))},
  "ops-13-division-sharing": {"rememberIt": R("Division = sharing equally OR making equal groups",
    "12 / 3: share 12 into 3 equal groups (4 each), or how many 3s fit in 12 (4). Remainder = leftovers."),
    "studentQuestions": Q(("What are the two meanings of division?", "Sharing equally (12 sweets among 3 kids = 4 each) OR grouping (how many 3s in 12 = 4)."),
                          ("What is a remainder?", "What is left over when it does not divide evenly. 13 / 4 = 3 remainder 1."))},
  "ops-15-word-problems": {"rememberIt": R("Read, spot the numbers, choose the operation, check the answer",
    "Clue words: total/altogether -> add; left/difference -> subtract; each/groups -> multiply or divide. Draw it!"),
    "studentQuestions": Q(("How do I pick the operation?", "Look for clue words: 'altogether' -> add, 'how many left' -> subtract, 'each' -> multiply/divide. Then check it makes sense."),
                          ("What if I am stuck?", "Draw a picture or use small numbers first. Modelling the story makes the operation obvious."))},
  "ops-16-division": {"rememberIt": R("Long division = DMSB: Divide, Multiply, Subtract, Bring down",
    "Work left to right through the digits, repeating DMSB, with a remainder at the end. 'Does McDonald's Sell Burgers?'"),
    "studentQuestions": Q(("How is long division organised?", "DMSB: Divide, Multiply, Subtract, Bring down, repeat."),
                          ("What do I do with a remainder?", "Leave it as 'r', or continue with a decimal point and zeros for an exact answer."))},
  "ops-17-properties": {"rememberIt": R("Three laws: Commutative (swap), Associative (regroup), Distributive (share out)",
    "a+b = b+a. (a+b)+c = a+(b+c). a(b+c) = ab+ac. They make mental maths easy."),
    "studentQuestions": Q(("What is the commutative property?", "You can swap the order: a+b = b+a and a x b = b x a. (Not for subtraction or division!)"),
                          ("What is the distributive property?", "Multiplying over a bracket: a(b+c) = ab + ac. 6x13 = 6x10 + 6x3 = 78 - a great mental trick."))},
  "found-01-prenumber": {"rememberIt": R("Before numbers: big/small, more/less, sort and match",
    "Compare sizes, match one-to-one, sort by colour or shape. This builds 'how many' before counting."),
    "studentQuestions": Q(("Why learn big/small before numbers?", "Comparing and sorting builds the sense of 'more' and 'less' - the ground counting stands on."),
                          ("What is one-to-one matching?", "Pairing each item with one other (a cup for each saucer) - it shows equal, more, or fewer without counting."))},
  "found-13-data": {"rememberIt": R("Sort things into groups, then count each group",
    "Put same with same, line them up, and see which group has more. The start of graphs."),
    "studentQuestions": Q(("What do I do first with a pile of things?", "Sort them into groups (by colour, shape...), then count each group to compare."),
                          ("How can I show my counts?", "Line the groups up, or draw one picture per item - a simple pictograph."))},
  "found-15-3d-shapes": {"rememberIt": R("Solid shapes you can hold: cube, sphere, cylinder, cone",
    "Ball = sphere (rolls), box = cuboid, tin = cylinder, party hat = cone. Notice flat faces vs curved."),
    "studentQuestions": Q(("How do I tell a cube from a sphere?", "A cube has flat square faces and corners; a sphere is round all over and rolls."),
                          ("Which 3D shapes roll?", "Sphere, cylinder, and cone - they have curved surfaces. A cube will not roll."))},
  "pp1-01-count-to-10": {"rememberIt": R("Touch and count: one number for each thing",
    "Say 1,2,3... touching each object once. The LAST number tells how many. Do not skip or double-count."),
    "studentQuestions": Q(("How do I count without missing any?", "Touch each thing once as you say the next number, and move it aside. The last number is the total."),
                          ("What does the last number tell me?", "How many there are altogether - the whole point of counting."))},
  "pp1-03-add-within-10": {"rememberIt": R("Adding = putting together. Count on from the bigger number",
    "3 + 5: start at 5, count on 3 -> 6,7,8. Fingers help. Order does not matter."),
    "studentQuestions": Q(("What's the easy way to add 3 + 5?", "Start from the bigger number (5) and count on: 6, 7, 8. Fewer steps than starting at 3."),
                          ("Does 3+5 equal 5+3?", "Yes - adding in any order gives the same total. So start from the bigger one."))},
  "pp1-04-subtract-within-10": {"rememberIt": R("Subtracting = taking away. Count back",
    "8 - 3: start at 8, count back 3 -> 7,6,5. Or 'how many more from 3 to 8?'. Fingers help."),
    "studentQuestions": Q(("How do I work out 8 - 3?", "Start at 8 and count back three: 7, 6, 5. Or count UP from 3 to 8 (also 5)."),
                          ("Is subtraction the opposite of adding?", "Yes - if 5 + 3 = 8, then 8 - 3 = 5. They undo each other."))},
}

changed = missing = 0
for cid, fields in DATA.items():
    path = INDEX.get(cid)
    if not path:
        print("MISSING:", cid); missing += 1; continue
    with open(path, "r", encoding="utf-8") as f:
        c = json.load(f)
    for k, v in fields.items():
        c[k] = v
    with open(path, "w", encoding="utf-8") as f:
        json.dump(c, f, ensure_ascii=False, indent=2)
    changed += 1

print("DONE changed=%d missing=%d total_in_data=%d" % (changed, missing, len(DATA)))
